language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose
  - cargo test --verbose -- --test-threads=1

notifications:
  email:
    on_success: never
